/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Mar 9 2016
 * Processor: PIC16F877A
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }